[package]
name = "battleship"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.21.0"
rand = "0.8.4"
array-init = "2.0"
itertools = "0.10"

[dev-dependencies]
assert_approx_eq = "1.1.0"
