[package]
name = "battleship-core"
version = "0.1.0"
edition = "2021"


[dependencies]
rand = "0.8"
array-init = "2.0"
battleship-common = { path = "../battleship-common" }
battleship-config = { path = "../battleship-config" }

[dev-dependencies]
assert_approx_eq = "1.1.0"
