[package]
name = "battleship-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
battleship-player = { path = "../battleship-player" }

[[bin]]
name = "battleship-sim"
path = "src/main.rs"

