[package]
name = "battleship-save"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
battleship-core = { path = "../battleship-core" }
battleship-common = { path = "../battleship-common" }



