[package]
name = "battleship-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
battleship-core = { path = "../battleship-core" }
battleship-transport = { path = "../battleship-transport" }
