[package]
name = "transport"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["sync", "net", "time"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
battleship_core = { package = "core", path = "../core" }
