[package]
name = "interface-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
battleship_core = { package = "core", path = "../core" }
